### ISSUE TITLE
[Player Footsteps] Include navblock in raycast layer matrix

### ISSUE THREAD

**Issue by calafex** [KacperObara/H3VRMods#1]
On my custom map I have floors that are made from navblock+noselfcol layers because I want sosigs to be able to see and shoot through but also walk on it (player too). Footsteps are not played on those because raycast only checks the environment layer. My proposal is to add navblock as well because it can be used to make floors too.

**Comment by KacperObara** [comment]
Sure, I've implemented Navblock check in 1.0.3.
Thanks for the feedback.
