### ISSUE TITLE
[Player Footsteps] Question Regarding Redistribution of Replacement Packs

### ISSUE THREAD

**Issue by RUSPY6** [KacperObara/H3VRMods#2]
Will Player Footsteps eventually become a library for modders to properly distribute their custom replacement packs, similar to PTNHBGML?

I've made quite a few replacement packs for the mod, using both free stock sounds, and ripped game audio. I'm assuming I should begin sharing them in the H3VR Homebrew as a simple .zip file to be extracted into another user's Player Footstep's resources folder, as repackaging your mod with the new audio would obviously contain a duplicate and eventually outdated .dll file.

**Comment by KacperObara** [comment]
Hey, since 1.1.0 the mod already supports this. 
Look at example mod I posted [here](https://thunderstore.io/c/h3vr/p/Kodeman/AlyxFootsteps/)

The original mod has quick tutorial but essentially change names of Your sound files and it will work. Just remember to set a dependency.
